apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: monitoring
spec:
  ports:
    - name: mqtt
      port: 1883
      nodePort: 31883
    - name: wss
      port: 9001
      nodePort: 32001
  selector:
    app: mosquitto
  type: NodePort
  externalTrafficPolicy: Local
# Use an loadBalancerIP (e.g. MetalLB) or externalIP depending on your setup
#  externalIPs:
#    - ${EI_MQTT}
